### ISSUE TITLE
How to redirect tenants?

### ISSUE THREAD

**Issue by 5starkarma** [tomturner/django-tenants#323] opened 2019-12-06 02:33 UTC
I am wondering about automatic routing tenants to their subdomain from the public schema. e.g. Tenant goes to www.example.com and tries to login, is their any solution in this app that routes them to their subdomain (www.tenant1.example.com)? I am sure this is a rather common question but for some reason I cannot find much on it.

In the docs I see Tenant View-Routing using PUBLIC_SCHEMA_URLCONF but I don't really understand exactly what this does.

I have also thought about using separate projects for the main website and tenants but then I would still need to either somehow grab the IP address of the user and try to route them to the correct subdomain or to ask them which subdomain they want (which seems inefficient and I dont want to give away that info).

So what do people do to solve this issue? I am almost positive there is a simple solution I am not seeing or simply not understanding as these seems like it would be a very common issue.

All help is very much appreciated :)

**Comment by webapp-dev** [comment] 2019-12-06 04:48
This is all handled by the authentication, so when a tenant user logs in they are authenticated across your system, all you need to do next is route them to their subdomain and they are already authenticated.

Not forgetting you should always have a unique decorator that checks their authentication against the tenant they are trying to access if they have rights allowing them to proceed, if not log them out and route them back to the main public website

I use django-tenant-users in concert with django-tenants this gives you double authentication, on the main website and also at the tenant level.

Always remember in a multi-tenancy setting you program the authentication checking and routing and in Django it is best done in a decorator.

Example: first test in the decorator is: are they authenticated?

        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse('user_login'))

The next test is: Do they have authentication at the tenancy they are trying to access? If No log them out and redirect to the main website

            if not request.user.has_tenant_permissions():
                logout(request) # user is trying to access someone else's account log them out
                return HttpResponseRedirect(reverse('main_site'))

Hope this helps.

**Comment by 5starkarma** [comment] 2019-12-06 05:30
First off, thank you very much for the response. I have been looking everywhere for this with no help. I am confused. To give more detail my tenants are companies on as shared apps and my users are tenant specific.. like this:

`
SHARED_APPS = [
    'django_tenants',
    'companies',  # tenants
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
]

TENANT_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'categories.apps.CategoriesConfig',
    'employees.apps.EmployeesConfig',  # users of tenants
    'memos.apps.MemosConfig',
    'invite.apps.InviteConfig',
    'videos.apps.VideosConfig',
    'crispy_forms',
    'quiz.apps.QuizConfig',
    'phonenumber_field',
    'phone_verify',
    'django_cleanup',
]`

When a user visits myexamplesite.com they are not able to log in because they are in the tenant specific app. Am I doing this wrong? Ideally I would like them to be able to login at myexamplesite.com and be automatically redirected to their tenant subdomain.

**Comment by webapp-dev** [comment] 2019-12-06 06:26
I think you need to check out django-tenant-users it works with django-tenants:
https://github.com/Corvia/django-tenant-users

It gives you authentication at both levels at the major site and at the tenancy level. 

SHARED_APPS=[
    # ...
    'django.contrib.auth', # Defined in both shared apps and tenant apps
    'django.contrib.contenttypes', # Defined in both shared apps and tenant apps
    'tenant_users.permissions', # Defined in both shared apps and tenant apps
    'tenant_users.tenants', # defined only in shared apps
    'customers', # Custom defined app that contains the TenantModel. Must NOT exist in TENANT_APPS
    'users', # Custom app that contains the new User Model (see below). Must NOT exist in TENANT_APPS
    # ...
]

TENANT_APPS=[
    # ...
    'django.contrib.auth', # Defined in both shared apps and tenant apps
    'django.contrib.contenttypes', # Defined in both shared apps and tenant apps
    'tenant_users.permissions', # Defined in both shared apps and tenant apps
    # ...
]

Then you can decide do they only get to login to your main website or can they login to a tenancy....
I have this working and I have clients limited to the main website and others who can own the tenancy accounts and yet others who can only login to the tenancy accounts.

This additional python lib will give you what you want.

**Comment by webapp-dev** [comment] 2019-12-06 06:36
As far as routing is concerned you can search which tenancy they are members of and if only one you can route them to that single tenancy or if they are members of multiple tenancies you can give them a list to choose.  Again using django-tenant-users you can search which tenancy they belong to and then route them to that tenancy. You need that extra library.

**Comment by webapp-dev** [comment] 2019-12-06 06:42
By the way I should have shown it as follows with the django-tenants in the shared apps and in addition to that you can see the django-tenant-users modules  ( tenant_users.permissions & tenant_users.tenants )

SHARED_APPS=[
# ...
django-tenants,
'django.contrib.auth', # Defined in both shared apps and tenant apps
'django.contrib.contenttypes', # Defined in both shared apps and tenant apps
'tenant_users.permissions', # Defined in both shared apps and tenant apps
'tenant_users.tenants', # defined only in shared apps
'customers', # Custom defined app that contains the TenantModel. Must NOT exist in TENANT_APPS
'users', # Custom app that contains the new User Model (see below). Must NOT exist in TENANT_APPS
# ...
]

TENANT_APPS=[
# ...
'django.contrib.auth', # Defined in both shared apps and tenant apps
'django.contrib.contenttypes', # Defined in both shared apps and tenant apps
'tenant_users.permissions', # Defined in both shared apps and tenant apps
# ...
]

**Comment by webapp-dev** [comment] 2019-12-06 06:56
Here is the description of django-tenants-users, it is exactly what you want:

This application expands the django users and permissions frameworks to work alongside django-tenant-schemas or django-tenants to allow global users with permissions on a per-tenant basis. This allows a single user to belong to multiple tenants and permissions in each tenant, including allowing permissions in the public tenant. This app also adds support for querying all tenants a user belongs to.

**Comment by kosz85** [comment] 2019-12-06 13:04
@webapp-dev how it will work with apps defined in both shared apps and tenant apps? You want have separate tables? How auth middleware is dealing with it? Not to mention request cached user, and such. I'm asking just because of curiosity, as we choose not to have such apps, as it's cleaner and safer in my opinion. Thats why in our app, we have auth only at shared (all users are defined in public schema).

**Comment by 5starkarma** [comment] 2019-12-06 14:22
@webapp-dev After reading the django-tenant-users docs this sounds exactly like what I am searching for. Thank you very much for taking the time to give detailed responses.

Before I begin integrating this module with my current system I need to handle the issue of the `django.contrib.auth` throwing the error: `django.db.utils.ProgrammingError: relation "django_content_type" does not exist` when switching the `auth` model to the public schema. 

Do you know why this happens? I am assuming it is because the `AUTH_USER_MODEL` is pointing to my `Employee(AbstractUser)` model which is a tenant specific app. Therefore, it can't reach it (being a separate schema). Is this correct? I don't want to start down a road until I understand why this happens.

**Comment by kosz85** [comment] 2019-12-06 14:47
@5starkarma no worries, I'm not serial murderer ;) If you put your model in shared apps, then the same data are available in all schemas (user table is in public schema). So same users would be available globally (single `"public"."account_user"` table). When you put it only in tenant apps, they are only locally in that tenant, and not available in public schema (multiple `"tenant_name"."account_user"` tables).
When you have it in both apps list, then you have all this table, and then it starts to be tricky, as postgres is taking first table found in `search_path`:
https://github.com/tomturner/django-tenants/blob/master/django_tenants/postgresql_backend/base.py#L146

So your local `"tenant_name"."account_user"` tables are overwriting your global one `"public"."account_user"` :) That's why I'm asking how it works. As in my opinion when you activate your tenant, `"tenant_name"."account_user"` will be empty.

The problem you experience is exactly problem of this type. Your `ContentType` is not aware of other tables. In fact it's more complicated, as CT has it's own cache and you need to clear it when you switch tenants, as your CT tables may have different content between different tenant. Someone can say it will be never different, but believe me it will be, due to migrations, removing models, and so on.
This cause that in one tenant model A has id 3 and in other tenant it has id 4 assigned to A and id 3 is assigned to model B, so when CT is using cache for second tenant it provides wrong ids, as cache has `A -> 3`, so it gives 3, but in fact it should return 4. We had exactly such problem when developing our app, and as a solution we removed CT from tenant schemas, and added manually all missing types.

In your case, you do not have `ContentType` table in public (shared) or tenants schema, you have it probably only locally in tenant.

I hope the whole idea is clearer now :) Do not be afraid to ask, just make more specific questions.

**Comment by 5starkarma** [comment] 2019-12-06 14:55
@kosz85 Really great explanation.. It seems that django-tenant-users may just be a monkey patch which may cause hidden but big bugs down the road - or just cause more problems than it is worth.

Going back to my original problem; I have a client which hates the idea of the users on his platform being required to go to subdomains to login. So what is the industry standard here? It seems from a security perspective that is exactly how it should be, right? Is there any good way to redirect tenant users to their specific subdomain without creating more problems?

**Comment by kosz85** [comment] 2019-12-06 15:15
@5starkarma I don't beleive that this lib is not working. I think it's use case is a bit different. I don't have time to analyze it now, maybe they solved it in some way. 
The easiest solution is to just move account and contenttype apps from `TENANT_APPS` to `SHARED_APPS`, but if you move account then users are shared, so you can't have 2 users of the same name, email etc. And if user is logging on `public` and have access to more then 1 tenant you 
 need to present list of tenants he want to access. This is our current solution. This also mean that we have one password for all tenants of single user.
In opposite you may leave it as is, and have totally separated users. But you will have multiple passwords too, and you are not aware at public schema about tenant users. There is no bad solution, you just need to be aware of how it works :)

I would ask you, why you want to login on public domain and then redirect? Why can't they log in at subdomain already? That would be my solution for your problem :)
But if you really hate it, then I suggest to make some custom solution, like postgres trigger on user create/update (in tenant user table), that will be adding/update row of (tenant_name, email or username) to some public table (you can access any other schema in raw sql queries). This way you will know which users have access to what tenants, but again you will have problem if one user is in more then one tenant, and then which password will you choose to check with? ;)
As always the worst problems are the border conditions, with single tenant per user it's easy, but then why not go with global user table? With multiple it's harder, for both solutions.
About how to redirect? Just overload log in view, and redirect, the problem is where to redirect, so knowing by email/username what tenant to choose.

Good option may be also a view over all schemas, that will create table matching user with tenant. That's good alternative to triggers, just different approach.

**Comment by 5starkarma** [comment] 2019-12-06 15:34
@kosz85 

>The easiest solution is to just move account and contenttype apps from TENANT_APPS to SHARED_APPS, but if you move account then users are shared, so you can't have 2 users of the same name, email etc.

So let me see if I understand this correctly; if I simply move these apps to `SHARED_APPS` then they will be able to login on the public schema and then I can find which tenant they belong to and redirect them to the correct subdomain accordingly to access the tenant specific apps. 

>In opposite you may leave it as is, and have totally separated users. But you will have multiple passwords too, and you are not aware at public schema about tenant users. There is no bad solution, you just need to be aware of how it works :)

I am fine with having one user/password across the whole system. In this case most users will be using their real name as usernames.

>I would ask you, why you want to login on public domain and then redirect? Why can't they log in at subdomain already? That would be my solution for your problem :)

The question is, how do I get the user to the subdomain to begin with? It seems like a good solution but there are going to be a lot of users that think www.example.com is where they should be logging in and in actuality they should be logging in at www.tenant1.example.com. This is the issue I will be facing. I want the users separated but not make the login process confusing for the tenant users.

>I just made fast look at https://github.com/Corvia/django-tenant-users and seems like they are solving it somehow with facades. I see there is nicely explained how it works, so read it. I'm not familiar with that app, and questions about why it's not working, should be made there. But if you want do it with standard django, then my comments should be on point.

I read the documentation. It seemed good at first but I had a little skepticism, then you drew a little more skepticism in me and I don't want to be unsure about things I do not fully understand.

**Comment by 5starkarma** [comment] 2019-12-06 15:47
Let's say I move the app containing this model to the `SHARED_APPS`:
```
class Employee(AbstractUser):
    """
    Store users, user-settings and meta-data, related to:

    :model: 'employees.EmployeeType'
    """
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    role = models.ForeignKey(
        EmployeeType,
        on_delete=models.CASCADE,
        blank=True,
        null=True)
    supervisor = models.ForeignKey(
        'self',
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='subordinates')
    company = models.ForeignKey(
        Company,
        on_delete=models.CASCADE,
        null=True,
        blank=True)
```

As long as `EmployeeType` and `Company` models are in `SHARED_APPS` I will be fine since they are handled on the public schema. And any models in `TENANT_APPS` can point to `Employee`, `EmployeeType` or `Company` without issue..

**Comment by 5starkarma** [comment] 2019-12-06 16:09
In all honesty, it seems that the most secure and simplest solution would be to set up a different project as the landing page then allow the user to select their tenant to redirect to subdomain, then user would be able to login at tenant subdomain from there without having to share users on public schema.

**Comment by kosz85** [comment] 2019-12-07 11:20
> So let me see if I understand this correctly; if I simply move these apps to SHARED_APPS then they will be able to login on the public schema and then I can find which tenant they belong to and redirect them to the correct subdomain accordingly to access the tenant specific apps. And as long as TENANT_APPS point to SHARED_APPS there will be no issues but I cannot point SHARED_APPS to TENANT_APPS..

Yes, and you can add related field to tenants or from tenants to users, to know which one belongs where. And add them to that relation when they create tenant, or invite other users to their tenant. In your case you can have tenants relation on User model.

> I am fine with having one user/password across the whole system. In this case most users will be using their real name as usernames.

Wrong! In short time you will have situation of 2 persons with name John Chang, email is much better, as it is and have to be unique.

> The question is, how do I get the user to the subdomain to begin with? It seems like a good solution but there are going to be a lot of users that think www.example.com is where they should be logging in and in actuality they should be logging in at www.tenant1.example.com. This is the issue I will be facing. Ideally I would have the users separated but not make the login process confusing for the tenant users.

It's simple, you have your User model with tenants M2M relation at public www.example.com. You log in user by email, and you have list of his tenants in relation. If it's single tenant you can redirect him directly to www.tenant1.example.com, if not, then you show him list of tenants (tenant1, tenant2) and redirect him after he sellect which tenant he want to access. It's simple `HttpResponseRedirect`:
https://docs.djangoproject.com/en/3.0/ref/request-response/#django.http.HttpResponseRedirect

The final choice, is your choice. If I would be doing it from start, I would prefer rather separate space of users and this postgres view over multiple tenant users. Sometimes users wants to have access to multiple tenants, but separated, but this depends of what you will do using this web app. Making it not separated can have it's own pluses too, by sharing some user configs.

**Comment by 5starkarma** [comment] 2019-12-07 15:38
This is a really good idea. I am going to apply this concept. Also, I reopened the issue so that people could find it in the search if they have the same issue. I see that only open issues are shown by default. Contributors feel free to close it if this is not the way this repo is set up.

**Comment by 5starkarma** [comment] 2019-12-07 18:03
If I move the `auth`, `contenttypes` and `user` apps to the `SHARED_APPS` it does what is expected - allowing user to create account and login across the tenants. This isn't actually what I want. I think what you are speaking about is SaaS ecosystems such as stackoverflow, stackexchange, etc where a user is global. I do not want users to be able to log in at tenants outside their own. Authentication needs to be done on a per tenant basis. :) All I want is a redirect from the public schema to the tenant schema if the user tries logging in at the public schema.

What I think I am going to do is add a simple model (e.g. PublicUsers) to the `SHARED_APPS` list with a FK to the Tenant model. When a user registers I will add their username to the PublicUsers model. I will then override the `auth` `LoginView` and add a check to make sure the username they are logging in with exists in the current schema. If it does then continue, if it does not then match the user's username with any name in the `PublicUsers` list, then redirect to their tenant accordingly.

**Comment by kosz85** [comment] 2019-12-08 13:21
You are thinking in wrong way. It's your app, you develop it, and you allow where user has access. You have relation on user which tenants he has access yes? Then create middleware to check if he has access to current tenant if it's not public. And if he doesn't you rise `HttpResponseForbidden`. It's that simple, users will have access only to their tenants.

**Closed** 2019-12-09 23:28 UTC

**Comment by erikvlm** [comment] 2019-12-22 08:07
@5starkarma did you find a solution to it? I'm having the exact same issues you're having.

I have found a way to redirect a user to the newly created schema (tenant), but I can't have them logged in automatically.

**Comment by ldonjibson** [comment] 2019-12-23 04:54
I dont know if this will help, but you can check this django package [`django-host`](https://github.com/jazzband/django-hosts)

**Comment by jayjunkyu** [comment] 2022-03-22 22:47
> @5starkarma did you find a solution to it? I'm having the exact same issues you're having.
> 
> I have found a way to redirect a user to the newly created schema (tenant), but I can't have them logged in automatically.
> 
> @kosz85 There might be some confusion here, but think Salesforce: https://login.salesforce.com/ Here, everyone can log in through login.salesforce.com with their respective username. If that username exists and they are successfully authenticated, they'll be redirected to something like https://my-production-tenancy.salesforce.com and logged in to that specific tenant domain
> 
> This is what OP is trying to achieve (and me)

I'm having the same problem, did `django-host` work?
